global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'car-management'
    static_configs:
      - targets: ['docker.for.mac.host.internal:8080']
    metrics_path: '/metrics'
    scheme: 'http'